spring:
  datasource:
    url: jdbc:mysql://localhost:3306/twitbook?characterEncoding=UTF-8&serverTimezone=UTC
    username: soojung
    password: jung0516
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true